/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VarietiesIndexRouteImport } from './routes/varieties/index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as VarietiesIdRouteImport } from './routes/varieties/$id'
import { Route as GroupsIdRouteImport } from './routes/groups/$id'
import { Route as VegetablesIdCompanionsRouteImport } from './routes/vegetables/$id.companions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VarietiesIndexRoute = VarietiesIndexRouteImport.update({
  id: '/varieties/',
  path: '/varieties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const VarietiesIdRoute = VarietiesIdRouteImport.update({
  id: '/varieties/$id',
  path: '/varieties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIdRoute = GroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VegetablesIdCompanionsRoute = VegetablesIdCompanionsRouteImport.update({
  id: '/vegetables/$id/companions',
  path: '/vegetables/$id/companions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups/$id': typeof GroupsIdRoute
  '/varieties/$id': typeof VarietiesIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/varieties/': typeof VarietiesIndexRoute
  '/vegetables/$id/companions': typeof VegetablesIdCompanionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups/$id': typeof GroupsIdRoute
  '/varieties/$id': typeof VarietiesIdRoute
  '/groups': typeof GroupsIndexRoute
  '/plan': typeof PlanIndexRoute
  '/varieties': typeof VarietiesIndexRoute
  '/vegetables/$id/companions': typeof VegetablesIdCompanionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups/$id': typeof GroupsIdRoute
  '/varieties/$id': typeof VarietiesIdRoute
  '/groups/': typeof GroupsIndexRoute
  '/plan/': typeof PlanIndexRoute
  '/varieties/': typeof VarietiesIndexRoute
  '/vegetables/$id/companions': typeof VegetablesIdCompanionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/$id'
    | '/varieties/$id'
    | '/groups/'
    | '/plan/'
    | '/varieties/'
    | '/vegetables/$id/companions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/groups/$id'
    | '/varieties/$id'
    | '/groups'
    | '/plan'
    | '/varieties'
    | '/vegetables/$id/companions'
  id:
    | '__root__'
    | '/'
    | '/groups/$id'
    | '/varieties/$id'
    | '/groups/'
    | '/plan/'
    | '/varieties/'
    | '/vegetables/$id/companions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsIdRoute: typeof GroupsIdRoute
  VarietiesIdRoute: typeof VarietiesIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  PlanIndexRoute: typeof PlanIndexRoute
  VarietiesIndexRoute: typeof VarietiesIndexRoute
  VegetablesIdCompanionsRoute: typeof VegetablesIdCompanionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varieties/': {
      id: '/varieties/'
      path: '/varieties'
      fullPath: '/varieties/'
      preLoaderRoute: typeof VarietiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varieties/$id': {
      id: '/varieties/$id'
      path: '/varieties/$id'
      fullPath: '/varieties/$id'
      preLoaderRoute: typeof VarietiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$id': {
      id: '/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof GroupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vegetables/$id/companions': {
      id: '/vegetables/$id/companions'
      path: '/vegetables/$id/companions'
      fullPath: '/vegetables/$id/companions'
      preLoaderRoute: typeof VegetablesIdCompanionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsIdRoute: GroupsIdRoute,
  VarietiesIdRoute: VarietiesIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  PlanIndexRoute: PlanIndexRoute,
  VarietiesIndexRoute: VarietiesIndexRoute,
  VegetablesIdCompanionsRoute: VegetablesIdCompanionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
