/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VegetablesIndexRouteImport } from './routes/vegetables/index'
import { Route as PlanIndexRouteImport } from './routes/plan/index'
import { Route as VegetablesIdRouteImport } from './routes/vegetables/$id'
import { Route as VegetablesIdCompanionsRouteImport } from './routes/vegetables/$id.companions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VegetablesIndexRoute = VegetablesIndexRouteImport.update({
  id: '/vegetables/',
  path: '/vegetables/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIndexRoute = PlanIndexRouteImport.update({
  id: '/plan/',
  path: '/plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const VegetablesIdRoute = VegetablesIdRouteImport.update({
  id: '/vegetables/$id',
  path: '/vegetables/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VegetablesIdCompanionsRoute = VegetablesIdCompanionsRouteImport.update({
  id: '/companions',
  path: '/companions',
  getParentRoute: () => VegetablesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vegetables/$id': typeof VegetablesIdRouteWithChildren
  '/plan/': typeof PlanIndexRoute
  '/vegetables/': typeof VegetablesIndexRoute
  '/vegetables/$id/companions': typeof VegetablesIdCompanionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vegetables/$id': typeof VegetablesIdRouteWithChildren
  '/plan': typeof PlanIndexRoute
  '/vegetables': typeof VegetablesIndexRoute
  '/vegetables/$id/companions': typeof VegetablesIdCompanionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vegetables/$id': typeof VegetablesIdRouteWithChildren
  '/plan/': typeof PlanIndexRoute
  '/vegetables/': typeof VegetablesIndexRoute
  '/vegetables/$id/companions': typeof VegetablesIdCompanionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vegetables/$id'
    | '/plan/'
    | '/vegetables/'
    | '/vegetables/$id/companions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vegetables/$id'
    | '/plan'
    | '/vegetables'
    | '/vegetables/$id/companions'
  id:
    | '__root__'
    | '/'
    | '/vegetables/$id'
    | '/plan/'
    | '/vegetables/'
    | '/vegetables/$id/companions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VegetablesIdRoute: typeof VegetablesIdRouteWithChildren
  PlanIndexRoute: typeof PlanIndexRoute
  VegetablesIndexRoute: typeof VegetablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vegetables/': {
      id: '/vegetables/'
      path: '/vegetables'
      fullPath: '/vegetables/'
      preLoaderRoute: typeof VegetablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/': {
      id: '/plan/'
      path: '/plan'
      fullPath: '/plan/'
      preLoaderRoute: typeof PlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vegetables/$id': {
      id: '/vegetables/$id'
      path: '/vegetables/$id'
      fullPath: '/vegetables/$id'
      preLoaderRoute: typeof VegetablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vegetables/$id/companions': {
      id: '/vegetables/$id/companions'
      path: '/companions'
      fullPath: '/vegetables/$id/companions'
      preLoaderRoute: typeof VegetablesIdCompanionsRouteImport
      parentRoute: typeof VegetablesIdRoute
    }
  }
}

interface VegetablesIdRouteChildren {
  VegetablesIdCompanionsRoute: typeof VegetablesIdCompanionsRoute
}

const VegetablesIdRouteChildren: VegetablesIdRouteChildren = {
  VegetablesIdCompanionsRoute: VegetablesIdCompanionsRoute,
}

const VegetablesIdRouteWithChildren = VegetablesIdRoute._addFileChildren(
  VegetablesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VegetablesIdRoute: VegetablesIdRouteWithChildren,
  PlanIndexRoute: PlanIndexRoute,
  VegetablesIndexRoute: VegetablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
