-- ---------------------------------------------------------------------------
-- Seed: vegetables
-- ---------------------------------------------------------------------------

INSERT INTO vegetables (id, latin_name, category, lifecycle, spacing_cm, days_to_harvest, days_to_plant, beginner_friendly, soil_types, sun_requirement, good_companions, bad_companions, calendars) VALUES

('tomato','Solanum lycopersicum','Fruit','Annual',60,75,42,true,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['basil','carrot','parsley','garlic','onion'],
 ARRAY['fennel','broccoli','cabbage'],
 '[{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["February","March"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["January","February"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May"],"indoor":["February","March"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May"],"indoor":["February","March"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}}]'),

('zucchini','Cucurbita pepo','Fruit','Annual',90,55,21,true,
 ARRAY['Loamy','Humus','Clay'],ARRAY['FullSun'],
 ARRAY['green-bean','maïs','radish','nasturtium'],
 ARRAY['potato'],
 '[{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["February","March"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}}]'),

('carrot','Daucus carota','Root','Annual',10,75,0,true,
 ARRAY['Sandy','Loamy'],ARRAY['FullSun','PartialShade'],
 ARRAY['tomato','onion','leek','lettuce','radish'],
 ARRAY['dill','fennel'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","June","July"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["February","March","April","May","June","July","August","September"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}}]'),

('basil','Ocimum basilicum','Herb','Annual',20,30,21,true,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['tomato','pepper','asparagus'],
 ARRAY['sage','thyme'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["April","May","June"],"indoor":["February","March"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Temperate","sowing":{"outdoor":["May","June"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["May","June"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('lettuce','Lactuca sativa','Leafy','Annual',30,45,21,true,
 ARRAY['Loamy','Humus','Clay'],ARRAY['PartialShade','FullSun'],
 ARRAY['carrot','radish','strawberry','cucumber'],
 ARRAY['parsley','celery'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","August","September"],"indoor":[]},"planting":{"outdoor":["April","May","August","September"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","May","August","September","October"],"indoor":[]},"planting":{"outdoor":["March","April","May","August","September","October"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","August","September"],"indoor":[]},"planting":{"outdoor":["April","May","August","September"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["February","March","April","May","August","September","October"],"indoor":[]},"planting":{"outdoor":["March","April","May","August","September","October"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":["May","June","July","August"],"indoor":[]}}]'),

('radish','Raphanus sativus','Root','Annual',5,25,0,true,
 ARRAY['Sandy','Loamy'],ARRAY['FullSun','PartialShade'],
 ARRAY['carrot','lettuce','tomato','cucumber'],
 ARRAY['hyssop'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","August","September"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","May","August","September","October"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","August","September"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["February","March","April","May","August","September","October"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}}]'),

('onion','Allium cepa','Bulb','Annual',10,100,60,true,
 ARRAY['Loamy','Sandy'],ARRAY['FullSun'],
 ARRAY['carrot','tomato','beet','lettuce'],
 ARRAY['green-bean','pea','garlic'],
 '[{"region":"Temperate","sowing":{"outdoor":["February","March","April","July","August"],"indoor":[]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["March","April","July","August"],"indoor":[]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","July","August","September"],"indoor":[]},"planting":{"outdoor":["March","April","May"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["February","March","April","July","August","September","October"],"indoor":[]},"planting":{"outdoor":["March","April","May"],"indoor":[]}}]'),

('garlic','Allium sativum','Bulb','Annual',10,240,0,true,
 ARRAY['Loamy','Sandy'],ARRAY['FullSun'],
 ARRAY['tomato','rose','strawberry','carrot'],
 ARRAY['onion','green-bean','pea'],
 '[{"region":"Temperate","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["October","November","March"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["September","October","November","February","March"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["October","November","March","April"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["October","November","December","March"],"indoor":[]}}]'),

('leek','Allium porrum','Bulb','Biennial',15,120,60,true,
 ARRAY['Loamy','Clay','Humus'],ARRAY['FullSun'],
 ARRAY['carrot','celery','lettuce'],
 ARRAY['green-bean','pea'],
 '[{"region":"Temperate","sowing":{"outdoor":["February","March","April"],"indoor":["January","February"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April"],"indoor":["January","November","December"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["March","April"],"indoor":["January","February"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["March","April","May"],"indoor":["February","March"]},"planting":{"outdoor":["June","July"],"indoor":[]}}]'),

('green-bean','Phaseolus vulgaris','Pod','Annual',15,55,0,true,
 ARRAY['Loamy','Sandy','Humus'],ARRAY['FullSun'],
 ARRAY['zucchini','maïs','potato','radish'],
 ARRAY['onion','garlic','fennel','leek'],
 '[{"region":"Temperate","sowing":{"outdoor":["April","May","June","July"],"indoor":[]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May","June","July"],"indoor":[]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["May","June","July"],"indoor":[]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":["April","May","June","July","August"],"indoor":[]}}]'),

('cucumber','Cucumis sativus','Fruit','Annual',60,55,21,true,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['radish','lettuce','green-bean','maïs'],
 ARRAY['tomato','potato','fennel'],
 '[{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["February","March"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('pepper','Capsicum annuum','Fruit','Annual',50,70,60,false,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['basil','tomato','carrot'],
 ARRAY['fennel','broccoli'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["January","February","March"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["February","March"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May"],"indoor":["February","March"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('pea','Pisum sativum','Pod','Annual',10,60,0,true,
 ARRAY['Loamy','Clay','Chalky'],ARRAY['FullSun','PartialShade'],
 ARRAY['carrot','radish','lettuce','cabbage'],
 ARRAY['onion','garlic','fennel'],
 '[{"region":"Temperate","sowing":{"outdoor":["February","March","April","September","October"],"indoor":[]},"planting":{"outdoor":["March","April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","September","October","November"],"indoor":[]},"planting":{"outdoor":["March","April","May"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["March","April","September"],"indoor":[]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["March","April","May","June"],"indoor":[]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('cabbage','Brassica oleracea','Leafy','Annual',50,90,35,false,
 ARRAY['Loamy','Clay','Chalky'],ARRAY['FullSun'],
 ARRAY['celery','onion','pea'],
 ARRAY['tomato','strawberry','fennel'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","July","August"],"indoor":["January","February"]},"planting":{"outdoor":["May","June","September","October"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","May","July","August"],"indoor":["January","February","November","December"]},"planting":{"outdoor":["April","May","June","September","October"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","July","August"],"indoor":["February","March"]},"planting":{"outdoor":["May","June","September"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["March","April","May","June"],"indoor":["February","March","April"]},"planting":{"outdoor":["June","July","August"],"indoor":[]}}]'),

('broccoli','Brassica oleracea var. italica','Leafy','Annual',50,80,35,false,
 ARRAY['Loamy','Clay','Chalky'],ARRAY['FullSun'],
 ARRAY['celery','onion'],
 ARRAY['tomato','pepper','strawberry'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","July","August"],"indoor":["January","February"]},"planting":{"outdoor":["May","June","September"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","July","August"],"indoor":["January","February"]},"planting":{"outdoor":["April","May","September","October"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","July","August"],"indoor":["February","March"]},"planting":{"outdoor":["May","June","September"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["April","May","June"],"indoor":["February","March","April"]},"planting":{"outdoor":["June","July"],"indoor":[]}}]'),

('parsley','Petroselinum crispum','Herb','Biennial',20,75,21,true,
 ARRAY['Loamy','Humus'],ARRAY['FullSun','PartialShade'],
 ARRAY['tomato','asparagus','rose'],
 ARRAY['lettuce'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","June","July","August"],"indoor":["January","February"]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","May","June","July","August","September"],"indoor":["January","February"]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","June","July"],"indoor":["February","March"]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["February","March","April","May","June","July","August","September","October"],"indoor":["January"]},"planting":{"outdoor":[],"indoor":[]}}]'),

('thyme','Thymus vulgaris','Herb','Perennial',30,90,28,true,
 ARRAY['Sandy','Chalky','Loamy'],ARRAY['FullSun'],
 ARRAY['cabbage','tomato','eggplant'],
 ARRAY['basil'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["March","April","May","June","July","August","September","October"],"indoor":[]},"planting":{"outdoor":["March","April","May","September","October"],"indoor":[]}},{"region":"Temperate","sowing":{"outdoor":["April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":["April","May","June","September"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","May","June","July","August","September"],"indoor":[]},"planting":{"outdoor":["April","May","June","September","October"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":["April","May","June"],"indoor":[]}}]'),

('rosemary','Salvia rosmarinus','Herb','Perennial',40,90,28,true,
 ARRAY['Sandy','Chalky'],ARRAY['FullSun'],
 ARRAY['cabbage','green-bean','sage'],
 ARRAY['cucumber','pumpkin'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["March","April","May","June","July","August","September","October","November"],"indoor":[]},"planting":{"outdoor":["March","April","May","September","October","November"],"indoor":[]}},{"region":"Temperate","sowing":{"outdoor":["March","April","May","June","July","August","September"],"indoor":[]},"planting":{"outdoor":["April","May","June","September"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","May","June","July","August","September","October"],"indoor":[]},"planting":{"outdoor":["April","May","June","September","October","November"],"indoor":[]}}]'),

('beet','Beta vulgaris','Root','Annual',15,60,0,true,
 ARRAY['Loamy','Sandy','Clay'],ARRAY['FullSun','PartialShade'],
 ARRAY['onion','lettuce','radish'],
 ARRAY['green-bean','mustard'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","June","July"],"indoor":[]},"planting":{"outdoor":["April","May","June","July"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":["April","May","June","July","August"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","June"],"indoor":[]},"planting":{"outdoor":["May","June","July"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["May","June","July"],"indoor":[]},"planting":{"outdoor":["June","July"],"indoor":[]}}]'),

('spinach','Spinacia oleracea','Leafy','Annual',15,40,0,true,
 ARRAY['Loamy','Humus','Clay'],ARRAY['PartialShade','FullSun'],
 ARRAY['strawberry','tomato','radish'],
 ARRAY['beet','sorrel'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","August","September","October"],"indoor":["January","February"]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","May","August","September","October","November"],"indoor":["January","February","November","December"]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["March","April","May","August","September"],"indoor":["February"]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["April","May","June","July","August"],"indoor":["March"]},"planting":{"outdoor":[],"indoor":[]}}]'),

('fennel','Foeniculum vulgare','Herb','Perennial',30,90,21,false,
 ARRAY['Loamy','Sandy'],ARRAY['FullSun'],
 ARRAY[]::TEXT[],
 ARRAY['tomato','green-bean','pepper','carrot','cabbage','pea','cucumber'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["March","April","May","June","August","September"],"indoor":[]},"planting":{"outdoor":["May","June","September","October"],"indoor":[]}},{"region":"Temperate","sowing":{"outdoor":["April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":["May","June","September"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May","June","July","August","September"],"indoor":[]},"planting":{"outdoor":["May","June","September","October"],"indoor":[]}}]'),

('eggplant','Solanum melongena','Fruit','Annual',60,75,60,false,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['basil','thyme','pepper'],
 ARRAY['fennel'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["February","March"]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["February","March"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('celery','Apium graveolens','Leafy','Biennial',30,100,60,false,
 ARRAY['Loamy','Humus','Clay'],ARRAY['FullSun','PartialShade'],
 ARRAY['leek','cabbage','tomato'],
 ARRAY['lettuce','garlic'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","June"],"indoor":["February","March"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","May","June"],"indoor":["February","March"]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","June"],"indoor":["March"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('potato','Solanum tuberosum','Root','Annual',35,90,0,true,
 ARRAY['Loamy','Sandy','Humus'],ARRAY['FullSun'],
 ARRAY['green-bean','cabbage','maïs'],
 ARRAY['tomato','cucumber','zucchini'],
 '[{"region":"Temperate","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["March","April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["March","April","May"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('maïs','Zea mays','Pod','Annual',40,80,0,true,
 ARRAY['Loamy','Humus','Clay'],ARRAY['FullSun'],
 ARRAY['green-bean','zucchini','potato'],
 ARRAY['tomato','celery'],
 '[{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["February","March"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('pumpkin','Cucurbita maxima','Fruit','Annual',120,100,21,false,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['maïs','green-bean','onion'],
 ARRAY['potato','rosemary'],
 '[{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["February","March"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('chive','Allium schoenoprasum','Herb','Perennial',20,60,21,true,
 ARRAY['Loamy','Humus'],ARRAY['FullSun','PartialShade'],
 ARRAY['carrot','tomato','rose','strawberry'],
 ARRAY['green-bean','pea'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","June","July","August"],"indoor":["January","February"]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","May","June","July","August"],"indoor":["January","February"]},"planting":{"outdoor":["March","April","May","June"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","June","July"],"indoor":["February","March"]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["April","May","June","July"],"indoor":["March","April"]},"planting":{"outdoor":["May","June"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April","May","June","July","August","September"],"indoor":["January","February"]},"planting":{"outdoor":["March","April","May","June","July"],"indoor":[]}}]'),

('mint','Mentha','Herb','Perennial',30,60,0,true,
 ARRAY['Loamy','Humus','Clay'],ARRAY['PartialShade','FullSun'],
 ARRAY['cabbage','tomato','pea'],
 ARRAY['parsley'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","June","July"],"indoor":[]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","May","June","July","August"],"indoor":[]},"planting":{"outdoor":["April","May","June","July"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","June","July"],"indoor":[]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["March","April","May","June","July","August","September"],"indoor":[]},"planting":{"outdoor":["March","April","May","June","July","August"],"indoor":[]}}]'),

('strawberry','Fragaria × ananassa','Fruit','Perennial',30,90,30,true,
 ARRAY['Loamy','Sandy','Humus'],ARRAY['FullSun','PartialShade'],
 ARRAY['lettuce','spinach','garlic','onion'],
 ARRAY['cabbage','fennel'],
 '[{"region":"Temperate","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["March","April","May","August","September"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["March","April","May","August","September","October"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["April","May","August","September"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":[],"indoor":[]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('turnip','Brassica rapa','Root','Annual',20,40,0,true,
 ARRAY['Loamy','Clay','Chalky'],ARRAY['FullSun','PartialShade'],
 ARRAY['pea','green-bean'],
 ARRAY['mustard','radish'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","July","August","September"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["February","March","April","May","July","August","September","October"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","August","September"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["May","June","July"],"indoor":[]},"planting":{"outdoor":[],"indoor":[]}}]'),

('cauliflower','Brassica oleracea var. botrytis','Leafy','Annual',60,80,35,false,
 ARRAY['Loamy','Clay','Chalky'],ARRAY['FullSun'],
 ARRAY['celery','onion','chive'],
 ARRAY['tomato','strawberry'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April","May","July","August"],"indoor":["January","February"]},"planting":{"outdoor":["May","June","September","October"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April","July","August"],"indoor":["January","February"]},"planting":{"outdoor":["April","May","September","October","November"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May","July","August"],"indoor":["February","March"]},"planting":{"outdoor":["May","June","September"],"indoor":[]}},{"region":"Mountain","sowing":{"outdoor":["May","June"],"indoor":["March","April"]},"planting":{"outdoor":["June","July"],"indoor":[]}}]'),

('red-pepper','Capsicum annuum','Fruit','Annual',50,70,60,false,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['basil','carrot','eggplant'],
 ARRAY['fennel'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["March","April"],"indoor":["January","February","March"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Temperate","sowing":{"outdoor":["April","May"],"indoor":["February","March"]},"planting":{"outdoor":["May","June"],"indoor":[]}}]'),

('asparagus','Asparagus officinalis','Leafy','Perennial',45,730,90,false,
 ARRAY['Sandy','Loamy'],ARRAY['FullSun'],
 ARRAY['tomato','parsley','basil'],
 ARRAY['onion','garlic'],
 '[{"region":"Temperate","sowing":{"outdoor":["March","April"],"indoor":["February"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["March","April"],"indoor":["February","March"]},"planting":{"outdoor":["April","May"],"indoor":[]}},{"region":"Continental","sowing":{"outdoor":["April","May"],"indoor":["March"]},"planting":{"outdoor":["May"],"indoor":[]}},{"region":"Mediterranean","sowing":{"outdoor":["February","March"],"indoor":["January","February"]},"planting":{"outdoor":["March","April","May"],"indoor":[]}}]'),

('artichoke','Cynara cardunculus var. scolymus','Leafy','Perennial',80,365,60,false,
 ARRAY['Loamy','Humus'],ARRAY['FullSun'],
 ARRAY['cabbage','lettuce'],
 ARRAY['green-bean','tomato'],
 '[{"region":"Mediterranean","sowing":{"outdoor":["March","April","May"],"indoor":["February","March"]},"planting":{"outdoor":["April","May","June"],"indoor":[]}},{"region":"Oceanic","sowing":{"outdoor":["April","May"],"indoor":["March","April"]},"planting":{"outdoor":["May","June","July"],"indoor":[]}}]');

-- ---------------------------------------------------------------------------
-- Seed: translations
-- ---------------------------------------------------------------------------

INSERT INTO vegetable_translations (vegetable_id, locale, name) VALUES
('tomato',     'en', 'Tomato'),
('tomato',     'fr', 'Tomate'),
('zucchini',   'en', 'Zucchini'),
('zucchini',   'fr', 'Courgette'),
('carrot',     'en', 'Carrot'),
('carrot',     'fr', 'Carotte'),
('basil',      'en', 'Basil'),
('basil',      'fr', 'Basilic'),
('lettuce',    'en', 'Lettuce'),
('lettuce',    'fr', 'Laitue'),
('radish',     'en', 'Radish'),
('radish',     'fr', 'Radis'),
('onion',      'en', 'Onion'),
('onion',      'fr', 'Oignon'),
('garlic',     'en', 'Garlic'),
('garlic',     'fr', 'Ail'),
('leek',       'en', 'Leek'),
('leek',       'fr', 'Poireau'),
('green-bean', 'en', 'Green Bean'),
('green-bean', 'fr', 'Haricot vert'),
('cucumber',   'en', 'Cucumber'),
('cucumber',   'fr', 'Concombre'),
('pepper',     'en', 'Pepper'),
('pepper',     'fr', 'Poivron'),
('pea',        'en', 'Pea'),
('pea',        'fr', 'Pois'),
('cabbage',    'en', 'Cabbage'),
('cabbage',    'fr', 'Chou'),
('broccoli',   'en', 'Broccoli'),
('broccoli',   'fr', 'Brocoli'),
('parsley',    'en', 'Parsley'),
('parsley',    'fr', 'Persil'),
('thyme',      'en', 'Thyme'),
('thyme',      'fr', 'Thym'),
('rosemary',   'en', 'Rosemary'),
('rosemary',   'fr', 'Romarin'),
('beet',       'en', 'Beet'),
('beet',       'fr', 'Betterave'),
('spinach',    'en', 'Spinach'),
('spinach',    'fr', 'Épinard'),
('fennel',     'en', 'Fennel'),
('fennel',     'fr', 'Fenouil'),
('eggplant',   'en', 'Eggplant'),
('eggplant',   'fr', 'Aubergine'),
('celery',     'en', 'Celery'),
('celery',     'fr', 'Céleri'),
('potato',     'en', 'Potato'),
('potato',     'fr', 'Pomme de terre'),
('maïs',       'en', 'Corn'),
('maïs',       'fr', 'Maïs'),
('pumpkin',    'en', 'Pumpkin'),
('pumpkin',    'fr', 'Citrouille'),
('chive',      'en', 'Chive'),
('chive',      'fr', 'Ciboulette'),
('mint',       'en', 'Mint'),
('mint',       'fr', 'Menthe'),
('strawberry', 'en', 'Strawberry'),
('strawberry', 'fr', 'Fraise'),
('turnip',     'en', 'Turnip'),
('turnip',     'fr', 'Navet'),
('cauliflower','en', 'Cauliflower'),
('cauliflower','fr', 'Chou-fleur'),
('red-pepper', 'en', 'Red Pepper'),
('red-pepper', 'fr', 'Poivron rouge'),
('asparagus',  'en', 'Asparagus'),
('asparagus',  'fr', 'Asperge'),
('artichoke',  'en', 'Artichoke'),
('artichoke',  'fr', 'Artichaut');
