/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/plan": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * POST /api/plan
     * @description Generates an optimised garden plan based on the provided constraints.
     */
    post: operations["post_plan"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/vegetables": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GET /api/vegetables
     * @description Returns all vegetables from the in-memory database.
     */
    get: operations["list_vegetables"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/vegetables/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GET /api/vegetables/{id}
     * @description Returns a single vegetable by id.
     */
    get: operations["get_vegetable"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/vegetables/{id}/companions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GET /api/vegetables/{id}/companions
     * @description Returns good and bad companions for a given vegetable.
     */
    get: operations["get_companions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Sowing or planting window — distinguishes direct outdoor from under-cover months. */
    CalendarWindow: {
      /** @description Months for sowing / planting under cover or in a greenhouse. */
      indoor: components["schemas"]["Month"][];
      /** @description Months for sowing / planting directly in open ground. */
      outdoor: components["schemas"]["Month"][];
    };
    /** @enum {string} */
    Category: "Fruit" | "Produce" | "Herb" | "Root" | "Bulb" | "Leafy" | "Pod";
    CompanionInfo: {
      id: string;
      name: string;
    };
    /** @description Generic single-item response envelope. */
    CompanionsApiResponse: {
      /** @description HAL-style hypermedia links. */
      _links: {
        [key: string]: components["schemas"]["Link"];
      };
      errors?: string[];
      payload: components["schemas"]["CompanionsResponse"];
    };
    CompanionsResponse: {
      bad: components["schemas"]["CompanionInfo"][];
      good: components["schemas"]["CompanionInfo"][];
      id: string;
      name: string;
    };
    /** @description A zero-based (row, col) position within the garden grid. */
    Coordinate: {
      col: number;
      row: number;
    };
    /** @description Error response returned for 4xx responses. */
    ErrorResponse: {
      error: string;
    };
    /**
     * @description A single cell in the **request** layout grid.
     *     Uses the same `{"type":...}` tag as `PlannedCell` but only carries the data
     *     relevant for input: `id` for pre-planted cells, nothing for `Empty`/`Blocked`.
     */
    LayoutCell:
      | {
          id: string;
          /**
           * Format: date
           * @description Date when this plant was put in the ground (ISO 8601, e.g. `"2025-05-01"`).
           *     When provided, it is used to free the cell after harvest and compute
           *     `estimatedHarvestDate` in the response.
           * @example 2025-05-01
           */
          planted_date?: string | null;
          /**
           * Format: int32
           * @description Number of plants per cell. Computed from the vegetable's spacing if absent.
           */
          plants_per_cell?: number | null;
          /** @enum {string} */
          type: "SelfContained";
        }
      | {
          id: string;
          /**
           * Format: int32
           * @description Block length in grid cells. Computed from the vegetable's spacing if absent.
           */
          length_cells?: number | null;
          /**
           * Format: date
           * @description Date when this plant was put in the ground (ISO 8601, e.g. `"2025-05-01"`).
           *     When provided, it is used to free the cell after harvest and compute
           *     `estimatedHarvestDate` in the response.
           * @example 2025-05-01
           */
          planted_date?: string | null;
          /**
           * Format: int32
           * @description Number of plants per cell. Computed from the vegetable's spacing if absent.
           */
          plants_per_cell?: number | null;
          /** @enum {string} */
          type: "Overflowing";
          /**
           * Format: int32
           * @description Block width in grid cells. Computed from the vegetable's spacing if absent.
           */
          width_cells?: number | null;
        }
      | {
          covered_by: components["schemas"]["Coordinate"];
          /** @enum {string} */
          type: "Overflowed";
        }
      | {
          /** @enum {string} */
          type: "Empty";
        }
      | {
          /** @enum {string} */
          type: "Blocked";
        };
    /** @enum {string} */
    Level: "Beginner" | "Expert";
    /**
     * @description Plant lifecycle: how many growing seasons the plant lives.
     * @enum {string}
     */
    Lifecycle: "Annual" | "Biennial" | "Perennial";
    /** @description A single HAL-style hyperlink. */
    Link: {
      href: string;
      /**
       * @description HTTP method to use for this link (e.g. `GET`, `POST`).
       * @example GET
       */
      method: string;
    };
    /**
     * @description Calendar month — used in sowing and planting windows.
     * @enum {string}
     */
    Month:
      | "January"
      | "February"
      | "March"
      | "April"
      | "May"
      | "June"
      | "July"
      | "August"
      | "September"
      | "October"
      | "November"
      | "December";
    /** @description Pagination metadata included in responses that return lists. */
    Pagination: {
      page: number;
      perPage: number;
      total: number;
      totalPages: number;
    };
    /** @description The date range of the planning period. */
    Period: {
      /**
       * Format: date
       * @description Last day of the planning period (ISO 8601, e.g. `"2025-08-31"`).
       * @example 2025-08-31
       */
      end: string;
      /**
       * Format: date
       * @description First day of the planning period (ISO 8601, e.g. `"2025-06-01"`).
       * @example 2025-06-01
       */
      start: string;
    };
    /** @description Generic single-item response envelope. */
    PlanApiResponse: {
      /** @description HAL-style hypermedia links. */
      _links: {
        [key: string]: components["schemas"]["Link"];
      };
      errors?: string[];
      payload: components["schemas"]["PlanResponse"];
    };
    PlanRequest: {
      /**
       * @description Vegetable IDs to exclude from planning — these will never be auto-placed
       *     regardless of other filters. Pre-placed cells in `layout` are not affected.
       */
      exclusions?: string[];
      /**
       * @description Combined grid layout — defines dimensions and pre-filled cells.
       *     Each cell is a `LayoutCell` object: `{"type":"Empty"}` (free),
       *     `{"type":"SelfContained","id":"..."}` (pre-planted), or `{"type":"Blocked"}` (blocked).
       */
      layout: components["schemas"]["LayoutCell"][][];
      level?: components["schemas"]["Level"] | null;
      period?: components["schemas"]["Period"] | null;
      /** @description Preferred vegetables with optional per-vegetable plant count. */
      preferences?: components["schemas"]["PreferenceEntry"][] | null;
      region: components["schemas"]["Region"];
      soil?: components["schemas"]["SoilType"] | null;
      /**
       * @description Vegetables already sown from seed, keyed by vegetable id.
       *     Each entry is a list of sowing batches, each with an optional date and a seed count.
       *     Example: `{ "tomato": [{ "sowingDate": "2025-03-15", "seedsSown": 10 }] }`
       */
      sown?: {
        [key: string]: components["schemas"]["SowingRecord"][];
      };
      sun?: components["schemas"]["SunExposure"] | null;
    };
    PlanResponse: {
      cols: number;
      rows: number;
      warnings: string[];
      /** @description One entry per week in the requested planning period. */
      weeks: components["schemas"]["WeeklyPlan"][];
    };
    /**
     * @description A cell in the planned garden grid (response output).
     *
     *     Three occupied variants, plus `Empty` and `Blocked`:
     *     - `SelfContained` - a plant whose spacing <= 30 cm; fits entirely in one cell.
     *     - `Overflowing`   - the anchor (top-left) cell of a plant that spans multiple cells.
     *     - `Overflowed`    - a continuation cell covered by a neighbouring anchor; carries only a
     *     back-reference so clients can look up the full data from the anchor.
     *     - `Empty`         - free, unoccupied, non-blocked cell.
     *     - `Blocked`       - non-plantable zone (path, alley, obstacle).
     */
    PlannedCell:
      | {
          /**
           * Format: date
           * @description Estimated date the plant will be ready to harvest.
           * @example 2025-08-01
           */
          estimated_harvest_date: string;
          id: string;
          name: string;
          /** Format: int32 */
          plants_per_cell: number;
          reason: string;
          /** @enum {string} */
          type: "SelfContained";
        }
      | {
          /**
           * Format: date
           * @description Estimated date the plant will be ready to harvest.
           * @example 2025-08-01
           */
          estimated_harvest_date: string;
          id: string;
          /** Format: int32 */
          length_cells: number;
          name: string;
          /** Format: int32 */
          plants_per_cell: number;
          reason: string;
          /** @enum {string} */
          type: "Overflowing";
          /** Format: int32 */
          width_cells: number;
        }
      | {
          covered_by: components["schemas"]["Coordinate"];
          /** @enum {string} */
          type: "Overflowed";
        }
      | {
          /** @enum {string} */
          type: "Empty";
        }
      | {
          /** @enum {string} */
          type: "Blocked";
        };
    /** @description A single preference entry with an optional desired plant count. */
    PreferenceEntry: {
      id: string;
      /**
       * Format: int32
       * @description Desired number of **plants** (placements) for this vegetable.
       *     Each plant may occupy more than one cell depending on its spacing.
       */
      quantity?: number | null;
    };
    /** @enum {string} */
    Region: "Temperate" | "Mediterranean" | "Oceanic" | "Continental" | "Mountain";
    /** @description Per-region sowing and planting calendar for a vegetable. */
    RegionCalendar: {
      planting: components["schemas"]["CalendarWindow"];
      region: components["schemas"]["Region"];
      sowing: components["schemas"]["CalendarWindow"];
    };
    /** @enum {string} */
    SoilType: "Clay" | "Sandy" | "Loamy" | "Chalky" | "Humus";
    /** @description One sowing event: an optional date and a seed count. */
    SowingRecord: {
      /**
       * Format: int32
       * @description Number of seeds (or seedlings) that were sown in this batch.
       */
      seedsSown: number;
      /**
       * Format: date
       * @description Date when the seeds were sown (ISO 8601, e.g. `"2025-03-15"`).
       *     When omitted the planner uses the vegetable's regional sowing calendar.
       * @example 2025-03-15
       */
      sowingDate?: string | null;
    };
    /**
     * @description A vegetable that should be sown during a given planning week so it is
     *     ready to transplant into the garden during a future week.
     */
    SowingTask: {
      /** @description Vegetable identifier. */
      id: string;
      /** @description Human-readable vegetable name. */
      name: string;
      /**
       * Format: date
       * @description Start date of the target transplanting week.
       * @example 2025-05-05
       */
      targetWeekStart: string;
    };
    /** @enum {string} */
    SunExposure: "FullSun" | "PartialShade" | "Shade";
    Vegetable: {
      badCompanions: string[];
      beginnerFriendly: boolean;
      /**
       * @description Per-region sowing and planting calendars.
       *     The presence of a [`RegionCalendar`] entry for a given region implies
       *     the vegetable can be grown there.
       */
      calendars: components["schemas"]["RegionCalendar"][];
      category: components["schemas"]["Category"];
      /**
       * Format: int32
       * @description Approximate number of days from planting/transplanting to first harvest.
       */
      daysToHarvest: number;
      /**
       * Format: int32
       * @description Approximate number of days from sowing a seed to being ready for transplanting outdoors.
       */
      daysToPlant: number;
      goodCompanions: string[];
      id: string;
      latinName: string;
      lifecycle: components["schemas"]["Lifecycle"];
      name: string;
      soilTypes: components["schemas"]["SoilType"][];
      /** Format: int32 */
      spacingCm: number;
      sunRequirement: components["schemas"]["SunExposure"][];
    };
    /** @description Generic single-item response envelope. */
    VegetableApiResponse: {
      /** @description HAL-style hypermedia links. */
      _links: {
        [key: string]: components["schemas"]["Link"];
      };
      errors?: string[];
      payload: components["schemas"]["VegetableResponse"];
    };
    /** @description Vegetable domain struct for use in responses. */
    VegetableResponse: components["schemas"]["Vegetable"] & Record<string, never>;
    /** @description Generic paginated list response envelope. */
    VegetablesApiResponse: {
      /** @description HAL-style hypermedia links. */
      _links: {
        [key: string]: components["schemas"]["Link"];
      };
      errors?: string[];
      pagination: components["schemas"]["Pagination"];
      payload: components["schemas"]["VegetableResponse"][];
    };
    /** @description A snapshot of the garden layout for one week of the planning period. */
    WeeklyPlan: {
      /** @description Full garden grid for this week (same dimensions as the request layout). */
      grid: components["schemas"]["PlannedCell"][][];
      period: components["schemas"]["Period"];
      /**
       * Format: int32
       * @description Cumulative companion-planting score for plants placed **this week**.
       */
      score: number;
      /**
       * @description Vegetables to sow this week so they are ready to transplant during a
       *     future planning week.
       */
      sowingTasks: components["schemas"]["SowingTask"][];
      /** Format: int32 */
      weekCount: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  post_plan: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Planning constraints and grid layout */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanRequest"];
      };
    };
    responses: {
      /** @description Optimised garden plan */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanApiResponse"];
        };
      };
      /** @description Validation error or bad JSON */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_vegetables: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of all vegetables */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VegetablesApiResponse"];
        };
      };
    };
  };
  get_vegetable: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Vegetable identifier (e.g. `tomato`, `basil`) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Vegetable found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VegetableApiResponse"];
        };
      };
      /** @description Vegetable not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_companions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Vegetable identifier (e.g. `tomato`) */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Companion planting info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompanionsApiResponse"];
        };
      };
      /** @description Vegetable not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
